spring.datasource.url=jdbc:sqlite:wildtype.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1
server.port=8081
server.tomcat.threads.virtual.enabled=true
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.thymeleaf.cache=false
wildtype.vision.enabled=true
