// /*
//  * This source file was generated by the Gradle 'init' task
//  */
// package org.wildtype;
//
// import org.junit.jupiter.api.Test;
// import static org.junit.jupiter.api.Assertions.assertNotNull;
//
// public class AppTest {
//     @Test
//     public void appHasAGreeting() {
//         App classUnderTest = new App();
//         assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//     }
// }
